import { 
    isNullOrEmpty,
    localtime,
    capitalizeFirstLetter,
    parseNumber,
    ifnullempty,
    isNumber,
    isNumberWithRequired,
    isNumberMaxDigitsWithRequired,
    countDecimals,
    translate,
    isDateIsoString,
    isDatetimeAwareIsoString,
    isStringWithMaxDigits,
    f,
} from "./src/functions.js";

import { 
    RulesDate,
    RulesDateIsoString,
    RulesDatetime,
    RulesDatetimeAwareIsoString,
    RulesEmail,
    RulesFloat,
    RulesFloatGEZ,
    RulesFloatGZ,
    RulesFloatLEZ,
    RulesInteger,
    RulesPassword,
    RulesSelection,
    RulesString,
} from "./src/rules.js";

export const vuetify_rules={
    isNullOrEmpty,
    localtime,
    capitalizeFirstLetter,
    parseNumber,
    ifnullempty,
    isNumber,
    isNumberWithRequired,
    isNumberMaxDigitsWithRequired,
    countDecimals,
    translate,
    isDateIsoString,
    isDatetimeAwareIsoString,
    isStringWithMaxDigits,
    f,
    RulesDate,
    RulesDateIsoString,
    RulesDatetime,
    RulesDatetimeAwareIsoString,
    RulesEmail,
    RulesFloat,
    RulesFloatGEZ,
    RulesFloatGZ,
    RulesFloatLEZ,
    RulesInteger,
    RulesPassword,
    RulesSelection,
    RulesString,
}

